# Generated by Django 5.0.6 on 2026-03-24 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicianprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinician_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='framecomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frame_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='framecomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='dashboard.framecomment'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='clinician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='dashboard.clinicianprofile'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientalert',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='dashboard.patientprofile'),
        ),
        migrations.AddField(
            model_name='patientalert',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='dashboard.pressureframe'),
        ),
        migrations.AddField(
            model_name='framecomment',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='dashboard.pressureframe'),
        ),
        migrations.AddField(
            model_name='pressuresession',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='dashboard.patientprofile'),
        ),
        migrations.AddField(
            model_name='pressureframe',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='dashboard.pressuresession'),
        ),
        migrations.AlterUniqueTogether(
            name='pressuresession',
            unique_together={('patient', 'source_file')},
        ),
        migrations.AlterUniqueTogether(
            name='pressureframe',
            unique_together={('session', 'frame_index')},
        ),
    ]
